name: Test
on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  build:
    name: test:build
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker-compose.yml
      USERNAME: ${{ secrets.DOCKER_USER }}
      PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        run: docker login -u $USERNAME -p $PASSWORD

      - name: Build docker images
        run: docker build . --file Dockerfile --tag yotsuba:$(date +%s) \
             --build-arg DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} \
             --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} \
             --build-arg CLIENT_ID=${{ secrets.CLIENT_ID }} \
  
  eslint:
    name: Run eslint scanning
    needs: [build]
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.1.0

      - uses: pnpm/action-setup@v2.2.3
        with:
          version: 7.11.0

      - name: Setup Node.js with pnpm
        uses: actions/setup-node@v3.5.0
        with:
          node-version: "16.x"
          cache: "pnpm"

      - name: Install ESLint
        run: |
          pnpm add eslint@8.10.0
          pnpm add @microsoft/eslint-formatter-sarif@2.1.7
      - name: Run ESLint
        run: pnpx eslint . --ext .js --config .eslintrc.json
        continue-on-error: true
